<table cellpadding='5' cellspacing='5'>
    <TR>
        <TD>&nbsp;</TD>
    </TR>

    <TR>
        <TD><img src='/control/images/deals.png' border='0'></TD>
        <TD class='red left'>Заказы</TD>
    </TR>
    <TR>
        <TD>&nbsp;</TD>
        <TD>
            <TABLE>
                <TR>
                    <TD><A href='/control/deals/' class='lnk'>Принятые</A></TD>
                </TR>
                <TR>
                    <TD><A href='/control/clients/?mode=c' class='lnk'>Клиенты</A></TD>
                </TR>
                <TR>
                    <TD><A href='/control/clients/?mode=d' class='lnk'>Дистрибьютеры</A></TD>
                </TR>
            </TABLE>
        </TD>
    </TR>

    <TR>
        <TD>&nbsp;</TD>
    </TR>

    <TR>
        <TD><img src='/control/images/catalog.png' border='0'></TD>
        <TD class='red left'>Каталог</TD>
    </TR>
    <TR>
        <TD>&nbsp;</TD>
        <TD>
            <TABLE>
                <TR>
                    <TD><A href='/control/produces/' class='lnk'>Позиции</A></TD>
                </TR>
                <TR>
                    <TD><A href='/control/produces/insert.php' class='lnk'>Добавить позицию</A></TD>
                </TR>
            </TABLE>
        </TD>
    </TR>

    <TR>
        <TD>&nbsp;</TD>
    </TR>

    <TR>
        <TD><img src='/control/images/article.png' border='0'></TD>
        <TD class='red left'>Материалы</TD>
    </TR>
    <TR>
        <TD>&nbsp;</TD>
        <TD>
            <TABLE>
                <TR>
                    <TD><A href='/control/articles/' class='lnk'>Материалы</A></TD>
                </TR>
                <TR>
                    <TD><A href='/control/articles/insert.php' class='lnk'>Добавить материал</A></TD>
                </TR>
            </TABLE>
        </TD>
    </TR>

    <TR>
        <TD>&nbsp;</TD>
    </TR>

    <TR>
        <TD><img src='/control/images/clients.png' border='0'></TD>
        <TD class='red left'>Подписки</TD>
    </TR>
    <TR>
        <TD>&nbsp;</TD>
        <TD>
            <TABLE>
                <TR>
                    <TD><A href='/control/subscribers/' class='lnk'>Подписчики</A></TD>
                </TR>
                <TR>
                    <TD><A href='/control/subscriptions/' class='lnk'>Подписки</A></TD>
                </TR>
            </TABLE>
        </TD>
    </TR>

    <TR>
        <TD>&nbsp;</TD>
    </TR>

    <TR>
        <TD><img src='/control/images/workers.png' border='0'></TD>
        <TD class='red left'>Структура</TD>
    </TR>
    <TR>
        <TD>&nbsp;</TD>
        <TD>
            <TABLE>
                <TR>
                    <TD><A href='/control/categories/' class='lnk'>Каталоги</A></TD>
                </TR>
                <TR>
                    <TD><A href='/control/categories/insert.php' class='lnk'>Добавить каталог</A></TD>
                </TR>
                <TR>
                    <TD>&nbsp;</TD>
                </TR>
                <TR>
                    <TD><A href='/control/subcategories/' class='lnk'>Подкаталоги</A></TD>
                </TR>
                <TR>
                    <TD><A href='/control/subcategories/insert.php' class='lnk'>Добавить подкаталог</A></TD>
                </TR>
                <TR>
                    <TD>&nbsp;</TD>
                </TR>
                <TR>
                    <TD><A href='/control/partitions/' class='lnk'>Разделы</A></TD>
                </TR>
                <TR>
                    <TD><A href='/control/partitions/insert.php' class='lnk'>Добавить раздел</A></TD>
                </TR>
            </TABLE>
        </TD>
    </TR>

    <TR>
        <TD>&nbsp;</TD>
    </TR>

    <TR>
        <TD><img src='/control/images/countries.png' border='0'></TD>
        <TD class='red left'>Яндекс</TD>
    </TR>
    <TR>
        <TD>&nbsp;</TD>
        <TD>
            <TABLE>
                <TR>
                    <TD><A href='/control/yandex/' class='lnk'>Каталог</A></TD>
                </TR>
                <TR>
                    <TD><A href='/control/yandex/insert.php' class='lnk'>Добавить позицию</A></TD>
                </TR>
                <TR>
                    <TD><A href='/control/yandex/upload.php' class='lnk'>Выгрузить каталог</A></TD>
                </TR>
            </TABLE>
        </TD>
    </TR>

<!--
    <TR>
        <TD>&nbsp;</TD>
    </TR>

    <TR>
        <TD><img src='/control/images/consult.png' border='0'></TD>
        <TD class='red left'>Консультации</TD>
    </TR>
    <TR>
        <TD>&nbsp;</TD>
        <TD>
            <TABLE>
                <TR>
                    <TD><A href='/control/consults/' class='lnk'>Вопросы</A></TD>
                </TR>
                <TR>
                    <TD><A href='/control/consults/insert.php' class='lnk'>Добавить вопрос</A></TD>
                </TR>
                <TR>
                    <TD>&nbsp;</TD>
                </TR>
                <TR>
                    <TD><A href='/control/comment/' class='lnk'>Отзывы</A></TD>
                </TR>
                <TR>
                    <TD><A href='/control/comment/insert.php' class='lnk'>Оставить отзыв</A></TD>
                </TR>
            </TABLE>
        </TD>
    </TR>

    <TR>
        <TD>&nbsp;</TD>
    </TR>
-->
</TABLE>