<table width="100%" border='0' cellpadding='0' cellspacing='0' align='center'>

    <TR>
        <TD style='vertical-align: top;'>
            <FORM method='post' name="cart_form">
                <INPUT type="hidden" name="rec" value="1">
                <TABLE border="0" cellpadding="0" cellspacing="0" align="center" width="700px">
                    <TR>
                        <TD valign='top' style='padding: 20px 30px 20px 0px;'>
                            <DIV style="padding:0 0 0 0; font-size: 20px" class="color_marsh">
                                <NOBR>Корзина покупок</NOBR>
                            </DIV>
                        </TD>
                    </TR>

                    <TR>
                        <TD style='vertical-align: top;'>
