<? /* @var CommentInsertView $this */
$comment = $this->getComment();
$captcha = $this->getCaptcha();
?>
<TABLE cellpadding='0' cellspacing='0' width='600' align='center' border='0'>
    <FORM method='post'>
        <INPUT type='hidden' name='item' value='<?= $comment->getItem()->getId() ?>'>
        <TR>
            <TD>
                <TABLE cellpadding='0' cellspacing='0' width='100%' border='0'>
                    <TR>
                        <TD align='left' class="color_marsh" style="font-size: 14px; padding: 0 0 10px 0;">
                            Представтесь
                        </TD>
                    </TR>
                    <TR>
                        <TD>
                            <INPUT class='input' type='text' name='name' size='30' maxlength='50'
                                   value='<?= $comment->getName() ?>'>
                        </TD>
                    </TR>
                </TABLE>
            </TD>
        </TR>
        <TR>
            <TD>
                <TABLE cellpadding='0' cellspacing='0' width='100%'>
                    <TR>
                        <TD class="color_marsh" style="font-size: 14px; padding: 10px 0 10px 0;">Ваше сообщение</TD>
                    <TR>
                    <TR>
                        <TD><TEXTAREA name='comment' cols='60' rows='5'
                                      maxlength='2500'><?= $comment->getComment() ?></TEXTAREA>
                        </TD>
                    </TR>
                </TABLE>
            </TD>
        </TR>
        <TR>
            <TD>
                <TABLE align='left' cellpadding='0' cellspacing='0' border='0'>
                    <TR>
                        <TD align='left' style="padding: 20px 20px 10px 0;"><IMG border="0" src="/captcha"></TD>
                        <TD align='left' style="padding: 20px 20px 10px 0;"><INPUT type="text" class="input"
                                                                                   name="validate"></TD>
                        <TD align='left' style="padding: 13px 20px 10px 0;">
                            <INPUT type='submit'
                                   class="backcolor_orange color_white"
                                   style="padding: 5px 10px 5px 10px;" name='rec' value='ОТПРАВИТЬ'>
                        </TD>
                    </TR>
                </TABLE>
            </TD>
        </TR>
    </FORM>
</TABLE>
