<? /* CabinetDealListView $this*/
$headerView = new CabinetHeaderView($this->customer);
$customerView = new CabinetCustomerInfoView($this->cart, $this->customer);
?>
<TABLE width="100%" border='0' cellpadding='0' cellspacing='0' align='center'>

    <TR>
        <TD style='vertical-align: top;'>
            <FORM method='post' name="cart_form">
                <INPUT type="hidden" name="rec" value="1">
                <TABLE border="0" cellpadding="0" cellspacing="0" align="center" width="700px">
                    <TR>
                        <TD valign='top' style='padding: 20px 30px 20px 0px;'>
                            <TABLE cellpadding="0" cellspacing="0" width="100%">
                                <TR>
                                    <TD style="padding:0 0 0 0; font-size:20px;" class="color_marsh">
                                        <NOBR>Ваш кабинет</NOBR>
                                    </TD>
                                    <TD style="padding:0 0 0 0; font-size:12px; width:30px; text-align:right;">
                                        <A href="/logout/" class="color_azure arial_family"
                                           style="text-decoration:underline;">Выйти</A>
                                    </TD>
                                </TR>
                            </TABLE>
                        </TD>
                    </TR>

                    <TR>
                        <TD><?= $headerView->view() ?></TD>
                    </TR>

                    <TR>
                        <TD><?= $customerView->view() ?></TD>
                    </TR>

                    <TR>
                        <TD style="padding:30px 0 0px 10px;" class="arial_family">Ваши заказы</TD>
                    </TR>

                    <TR>
                        <TD style="padding:20px 0 60px 0;">
                            <table class='original_cabinet_table' cellpadding='0' cellspacing='0' border='0'
                                   width='100%'>
                                <TR>
                                    <TH>No \ Статус</TH>
                                    <TH>Дата</TH>
                                    <TH>Стоимость</TH>
                                    <TH>Имя заказчика</TH>
                                    <TH>Адрес</TH>
                                </TR>