<SCRIPT type="text/javascript" src="/jquery_plugins/slide_gallery/jquery.history.js"></SCRIPT>
<SCRIPT type="text/javascript" src="/jquery_plugins/slide_gallery/jquery.js"></SCRIPT>
<SCRIPT type="text/javascript" src="/jquery_plugins/slide_gallery/main.js"></SCRIPT>

<LINK rel="stylesheet" type="text/css" href="/jquery_plugins/slide_gallery/style.css">

<div id='content'>
    <div id='service'>
        <div class='gallery'>
            <ul>
                <li class='active'>
                    <img src='/images/club_slider/1.jpg'/>
                </li>
                <li class='active'>
                    <img src='/images/club_slider/2.jpg'/>
                </li>
                <li class='active'>
                    <img src='/images/club_slider/3.jpg'/>
                </li>
                <li class='active'>
                    <img src='/images/club_slider/4.jpg'/>
                </li>
                <li class='active'>
                    <img src='/images/club_slider/5.jpg'/>
                </li>
                <li class='active'>
                    <img src='/images/club_slider/6.jpg'/>
                </li>
                <li class='active'>
                    <img src='/images/club_slider/7.jpg'/>
                </li>
                <li class='active'>
                    <img src='/images/club_slider/8.jpg'/>
                </li>
                <li class='active'>
                    <img src='/images/club_slider/9.jpg'/>
                </li>
                <li class='active'>
                    <img src='/images/club_slider/10.jpg'/>
                </li>
                <li class='active'>
                    <img src='/images/club_slider/11.jpg'/>
                </li>
                <li class='active'>
                    <img src='/images/club_slider/12.jpg'/>
                </li>
                <li class='active'>
                    <img src='/images/club_slider/13.jpg'/>
                </li>
            </ul>
            <div class='controls'>
                <div class='play'>
                </div>
                <div class='prev'>
                </div>
                <div class='next'>
                </div>
            </div>
            <div class='counter'>
                <div class='item'></div>
                <div class='item'></div>
                <div class='item'></div>
                <div class='item'></div>
                <div class='item'></div>
                <div class='item'></div>
                <div class='item'></div>
                <div class='item'></div>
                <div class='item'></div>
                <div class='item'></div>
                <div class='item'></div>
                <div class='item'></div>
                <div class='item'></div>
                <div class='item active'></div>
            </div>
        </div>
    </div>
</div>
