<TABLE width="100%" border='0' cellpadding='0' cellspacing='0' align='center'>


    <TR>
        <TD style='vertical-align: top;'>
            <TABLE border="0" cellpadding="0" cellspacing="0" align="center" width="700px">
                <TR>
                    <TD valign='top' style='padding: 20px 30px 20px 0px;'>
                        <DIV style="padding:0 0 0 0; font-size: 20px" class="color_marsh">
                            <NOBR>Ваш заказ принят</NOBR>
                        </DIV>
                    </TD>
                </TR>
                <TR>
                    <TD style='vertical-align:top; height:350px; text-align: left;'>
                        <DIV style='padding: 30px 20px 0 0; font-size: 14px;' class='color_brown arial_family'>
                            В ближайшее время наши менеджеры свяжутся с вами.
                            </DIV>
                        <DIV style='padding: 10px 20px 0 0; font-size: 14px;' class='color_brown arial_family'>
                            Перейти в
                            <A href='/cabinet/' class='color_orange' style='font-size: 14px;'>Личный кабинет</A>
                        </DIV>
                    </TD>
                </TR>
            </TABLE>
        </TD>
    </TR>
</TABLE>