<? /* @var ProduceSubscribeFormView $this */
$subscriber = $this->getSubscriber();

$resultId = $this->getResultId();
$parentResultId = $this->getParentId();

$subscriberRepresent = new SubscriberViewRepresent($this->subscriber);
?>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
<FORM action="/produce_notice_subscribe/" method="post" id="noticeForm" name="noticeForm">
    <INPUT type="hidden" name="subscriber" value="<?= $subscriber->getId() ?>">
    <INPUT type="hidden" name="subscriber_type" value="<?= $subscriber->getSubscriberType()->getCode() ?>">
    <INPUT type="hidden" name="item" value="<?= $this->getProduce()->getId() ?>"/>

    <TABLE cellpadding="0" cellspacing="0" border="0" align="center"
           style="text-align:left; width:100%;" class="backcolor_white bordercolor_lightgray">
        <TR>
            <TD class="color_marsh"
                style="font-size: 18px; text-align:center; width:250px; padding:30px 40px 0px 40px;">
                УВЕДОМЛЕНИЕ О НАЛИЧИИ
            </TD>
        </TR>
        <TR>
            <TD class="color_gray" style="font-size: 16px; text-align:center; padding: 20px 0 0 0;">
                <INPUT
                    class="input bordercolor_lightgray color_orange"
                    style='border-width:1px; width:200px; text-align:center; font-size: 16px; height:30px;'
                    name="name"
                    value="<?= $subscriberRepresent->getName() ?>" <?= $subscriberRepresent->getBlocked() ?> <?= $subscriberRepresent->getOnClick() ?>>
            </TD>
        </TR>
        <TR>
            <TD class="color_gray" style="font-size: 16px; text-align:center; padding: 20px 0 0 0;">
                <INPUT
                    class="input bordercolor_lightgray color_orange"
                    style='border-width:1px; width:200px; text-align:center; font-size:16px; height:30px;'
                    name="email"
                    value="<?= $subscriberRepresent->getEmail() ?>" <?= $subscriberRepresent->getBlocked() ?> <?= $subscriberRepresent->getOnClick() ?>>
            </TD>
        </TR>
        <TR>
            <TD class="color_warmgray"
                style="font-size: 16px; vertical-align: middle; text-align:center; padding: 20px 0 40px 0;"><A
                    href="javascript:void(0);" style="text-decoration: none;">
                    <INPUT type="button" class="backcolor_orange bordercolor_orange color_white"
                           style="font-size: 16px; display: inline; padding:5px 39px 2px 39px;cursor: pointer;"
                           onClick="if(validate(noticeForm)) {
                               ajaxPostRequest('/produce_notice_subscribe/', 'noticeForm', '<?= $resultId ?>', '<?= $parentResultId ?>', true);
                               }
                               return false;"
                           value="ПОЛУЧАТЬ"/>
            </TD>
        </TR>

        <TR>
            <TD style="text-align:right; padding: 0 10px 5px 0; font-size:12px;">
                <A href="javascript:void(0);" class="color_red arial_family"
                   onClick="hideElementBy('<?= $resultId ?>'); restoreElement('<?= $parentResultId ?>'); return false;">закрыть</A>
            </TD>
        </TR>
    </TABLE>
</FORM>