<? /* @var CustomerInsertDealView $this */
$deal = $this->getDeal();
$distibuiton = (strlen($deal->getCustomer()->getDistributon()) > 0) ?
    "номер дистрибьютера: " . $deal->getCustomer()->getDistributon() : "";
?>
<form name='order' method='post' action='/control/clients/insert_deal.php' enctype='multipart/form-data'>
    <INPUT type='hidden' name='customer' value='<?= $deal->getCustomer()->getId() ?>'/>
    <INPUT type='hidden' name='address' value='<?= $deal->getAddress()->getId() ?>'/>
    <TABLE cellSpacing=0 cellPadding=0 width="100%" align=center border=0>
        <TR>
            <TD style='padding:0 0 20 0;'><FONT class="switch font17 color2">Покупатель</FONT></TD>
        </TR>
        <TR>
            <TD>
                <table cellpadding='10' cellspacing='10' border='0'>
                    <TR>
                        <TD class='date red' align='right'>Имя</TD>
                        <TD class='txt black'>
                            <?= $deal->getCustomer()->getName() ?>&nbsp;<?= $distibuiton ?>
                        </TD>
                    </TR>
                    <TR>
                        <TD class='date red' align='right'>Телефон</TD>
                        <TD class='txt black'><?= $deal->getAddress()->getPhone() ?>
                            &nbsp;<?= $deal->getCustomer()->getPhone() ?></TD>
                    </TR>
                    <TR>
                        <TD class='date red' align='right'>E-mail</TD>
                        <TD class='txt black'><?= $deal->getCustomer()->getEmail() ?></TD>
                    </TR>
                    <TR>
                        <TD class='date red' align='right'>Адрес</TD>
                        <TD class='txt black'><?= $deal->getAddress()->toDetailString() ?></TD>
                    </TR>
                </TABLE>
            </TD>
        </TR>

        <TR>
            <TD>&nbsp;</TD>
        </TR>

        <TR>
            <TD style='padding:0 0 20 0;'><FONT class="switch font17 color2">Информация о заказе</FONT></TD>
        </TR>
        <TR>
            <TD>
                <table class='original_table' cellpadding='0' cellspacing='0' border='0' width='70%'>
                    <TR>
                        <TH>No.</TH>
                        <TH align='left'>Наименование</TH>
                        <TH align=center>Кол-во</TH>
                    </TR>
