<?/* @var CategoryFilterView $this */
$filter = $this->getFilter();
?>
<form name='search' method='post' action='<?= $filter->getNavigation()->getUrl() ?>/'>
    <TABLE width='98%' align='center'>
        <TR>
            <TD>
                <FONT class="switch font17 color2">Каталоги</FONT>
            </TD>
        </TR>
        <TR>
            <TD>
                <TABLE align='left' cellpadding='5' cellspacing='5'>
                    <TR>
                        <TD class="date red">Тип</TD>
                        <TD>
                            <SELECT class='input' name='type' style='width:300px;'>
                                <?
                                /* @var CategoryType $item */
                                foreach (CategoryType::getAllItems("CategoryType") as $item) {
                                    $arParams = $item->getParams();
                                    $selected = ($item->equals($filter->getType())) ? "selected" : "";
                                    echo "<option value='" . $item->getCode() . "' $selected>" . $arParams['description'] . "</OPTION>";
                                }
                                ?>
                            </SELECT>
                        </TD>
                    </TR>
                </TABLE>
            </TD>
        </TR>
        <TR>
            <TD class="yellow_foot line_divs">
                <TABLE cellpadding='0' cellsapcing='0' border='0'>
                    <TR>
                        <TD style='padding: 0 0 0 40px;'>
                            <INPUT class="big_button" name='tser' type="submit" value="Показать">
                        </TD>
                        <TD style='padding: 0 0 0 40px;'>
                            <INPUT class="big_button" name='tres' type="submit" value="Показать все">
                        </TD>
                    </TR>
                </TABLE>
            </TD>
        </TR>
    </TABLE>
</FORM>